<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Staff Directory Export</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .header {
            margin-bottom: 20px;
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 10px;
        }
        .header table {
            width: 100%;
        }
        .title {
            font-size: 18px;
            font-weight: bold;
            color: #1e1b4b;
        }
        .meta-text {
            font-size: 10px;
            color: #666;
            text-align: right;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .data-table th {
            background-color: #f3f4f6;
            color: #1e293b;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9px;
            border: 1px solid #e5e7eb;
            padding: 8px 6px;
            text-align: left;
        }
        .data-table td {
            border: 1px solid #e5e7eb;
            padding: 6px;
            font-size: 9.5px;
            color: #334155;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 9px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td>
                    <div class="title">Staff Directory Export</div>
                    <div style="font-size: 10px; color: #6366f1; margin-top: 2px;">Leena IT Solutions - Salary Manager</div>
                </td>
                <td class="meta-text">
                    Generated: {{ date('d-m-Y H:i A') }}<br>
                    Total Records: {{ count($employees) }}
                </td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                @foreach ($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($employees as $employee)
                <tr>
                    @foreach ($fields as $field)
                        <td>
                            @switch($field)
                                @case('department')
                                    {{ optional($employee->employee_department)->department ? $employee->employee_department->department->department : '—' }}
                                    @break
                                @case('designation')
                                    {{ optional($employee->employee_designation)->designation ? $employee->employee_designation->designation->designation : '—' }}
                                    @break
                                @case('work_location')
                                    {{ optional($employee->employee_work_location)->work_location ? $employee->employee_work_location->work_location->location_name : '—' }}
                                    @break
                                @default
                                    {{ $employee->$field ?? '—' }}
                                    @break
                            @endswitch
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential - Internal HR Document - Generated by Salary Manager PWA
    </div>
</body>
</html>
